version: "3.9"

services:
  mongo:
    ports:
      - "27017:27017"

  backend:
    ports:
      - "4000:4000"
    environment:
      CLIENT_URL: http://localhost:3000

  ai-service:
    ports:
      - "5001:5001"

  client:
    ports:
      - "3000:3000"
